PLAYER_1 = 'White'
PLAYER_1_PIECES = ['WP0', 'WN0', 'WB0', 'WRK', 'WRQ', 'WQ0', 'WK0']
PLAYER_2 = 'Black'
PLAYER_2_PIECES = ['BP0', 'BN0', 'BB0', 'BRK', 'BRQ', 'BQ0', 'BK0']
EMPTY = '000'
RANKS = 8
FILES = 8

W_PAWN = 'WP0'
W_KNIGHT = 'WN0'
W_BISHOP = 'WB0'
# W_ROOK = 'WR'
W_KING_ROOK = 'WKR'
W_QUEEN_ROOK = 'WQR'
W_QUEEN = 'WQ0'
W_KING = 'WK0'

B_PAWN = 'BP0'
B_KNIGHT = 'BN0'
B_BISHOP = 'BB0'
# B_ROOK = 'BR'
B_KING_ROOK = 'BKR'
B_QUEEN_ROOK = 'BQR'
B_QUEEN = 'BQ0'
B_KING = 'BK0'
